# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  check_run:
  push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-ubuntu:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: submodules-init
      uses: snickerbockers/submodules-init@v4

    - name: Setup BATS testing framework
      uses: mig4/setup-bats@v1.2.0
      with:
        # The BATS version to setup. Example: 1.0.0 or master, default: 1.1.0
        bats-version: 1.5.0

    # Run Shellcheck
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
      with:
        ignore_paths: vendor stub package.sh
        severity: warning

    # Runs BATS tests
    - name: Run BATS tests
      run: BASHER_ROOT=${GITHUB_WORKSPACE}/stub/basher BASHER_PREFIX=${GITHUB_WORKSPACE}/stub TERM=xterm bats tests

  build-macos:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: submodules-init
      uses: snickerbockers/submodules-init@v4

    - name: Setup BATS testing framework
      uses: mig4/setup-bats@v1.2.0
      with:
        # The BATS version to setup. Example: 1.0.0 or master, default: 1.1.0
        bats-version: 1.5.0

    # Runs BATS tests
    - name: Run BATS tests
      run: BASHER_ROOT=${GITHUB_WORKSPACE}/stub/basher BASHER_PREFIX=${GITHUB_WORKSPACE}/stub TERM=xterm bats tests
